// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRkRJZGygVhwcWp6muHcirwJI05-NkRHQ',
    appId: '1:654804660349:web:7615717f0f37a4ebf80114',
    messagingSenderId: '654804660349',
    projectId: 'best-inox',
    authDomain: 'best-inox.firebaseapp.com',
    storageBucket: 'best-inox.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzhDw4TTOFmhcOU2wlKdfrVDSCKtxpfHw',
    appId: '1:654804660349:android:3d01bec6f5179876f80114',
    messagingSenderId: '654804660349',
    projectId: 'best-inox',
    storageBucket: 'best-inox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbVcceqFWZ0uF1nGwxrqhRY8LW7rgVDbU',
    appId: '1:654804660349:ios:5db766a97bfb9484f80114',
    messagingSenderId: '654804660349',
    projectId: 'best-inox',
    storageBucket: 'best-inox.appspot.com',
    iosClientId:
        '654804660349-lfiq12mm6m707vh4damc8tflso763vk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestInox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbVcceqFWZ0uF1nGwxrqhRY8LW7rgVDbU',
    appId: '1:654804660349:ios:5db766a97bfb9484f80114',
    messagingSenderId: '654804660349',
    projectId: 'best-inox',
    storageBucket: 'best-inox.appspot.com',
    iosClientId:
        '654804660349-lfiq12mm6m707vh4damc8tflso763vk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bestInox',
  );
}
